---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: ibm-mq
spec:
  template:
    spec:
      containers:
        - image: index.docker.io/triggermesh/ibm-mq-source-d3d8bd60b2ba9d2f4fbe4857fe0a0dd7
          name: receiver
          env:
            - name: LD_LIBRARY_PATH
              value: /var/run/ko/lib64
            - name: QUEUE_MANAGER
              value: QM1
            - name: CHANNEL_NAME
              value: DEV.APP.SVRCONN
            - name: CONNECTION_NAME
              value: mq-service.default.svc.cluster.local(1414)
            - name: QUEUE_NAME
              value: DEV.QUEUE.1
            # Insert IBM MQ user access credentials
            - name: USER_ID
            - name: PASSWORD
  sink:
    # Replace following reference with your event receiver
    # It can be knative service, broker or channel
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
